language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
sudo: required
addons:
  apt:
    packages:
      gradle
jobs:
  include:
    - stage: Compilation
      script: ./gradlew build
    - stage: Generate Jar
      script: ./gradlew jar
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_KEY
  file: 
    - "$TRAVIS_BUILD_DIR/build/distributions/LocalPrinting.zip"
    - "$TRAVIS_BUILD_DIR/build/distributions/LocalPrinting.tar"
  skip_cleanup: true
  on:
    tags: true